print_freq: 100
output_dir: './logs'
checkpoint_freq: 10


sync_bn: True
find_unused_parameters: True


use_amp: False
scaler:
  type: GradScaler
  enabled: True


use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
